# Generated by Django 4.0 on 2021-12-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
    ]
